### ISSUE TITLE
When a package is a "devDependencies", add it to devDependencies in root

### ISSUE THREAD

**Issue by hindsjay** [zensurance/deup#27]
It appears when deduping we're only adding the dependency to "dependencies" at the root level.  If it's a "devDependency" this will still get added to "dependencies" at the root level (which I'm not sure we want).

The impact is as more dedupes happen the "dependencies" list will have a lot of packages that were meant to be "devDependencies", unless the person working on the dedupe manually moves it over.

If the package was under `devDependencies` originally it should be added to `devDependencies` when running the script.

I did a test where I ran the script to dedupe `@percy/storybook` which is a "devDependency" and it was added to "dependencies" at the root level.

**Comment by felipeplets** [comment]
Thank you for the contribution @hindsjay
